export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//SharedActions
export const LOG_ERROR_SUCCESS = 'LOG_ERRROR_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_CUSTOM_USER_SUCCESS = 'LOAD_CUSTOM_USER_SUCCESS';
export const LOAD_APP_PROPERTIES_SUCCESS = 'LOAD_APP_PROPERTIES_SUCCESS';
export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS';
export const LOAD_MENU_OPTIONS_SUCCESS = 'LOAD_MENU_OPTIONS_SUCCESS';
export const UPDATE_MENU_OPTIONS_SUCCESS = 'UPDATE_MENU_OPTIONS_SUCCESS';
export const UPDATE_USER_CAMPUS_SUCCESS = 'UPDATE_USER_CAMPUS_SUCCESS';
export const UPDATE_USER_HOME_PAGE_SUCCESS = 'UPDATE_USER_HOME_PAGE_SUCCESS';
export const LOAD_SCHOOL_YEAR_TYPES_SUCCESS = 'LOAD_SCHOOL_YEAR_TYPES_SUCCESS';
//Campus
export const LOAD_ALL_CAMPUSES_SUCCESS = 'LOAD_ALL_CAMPUSES_SUCCESS';
export const LOAD_CAMPUSES_BY_MANAGER_SUCCESS = 'LOAD_CAMPUSES_BY_MANAGER_SUCCESS';
export const LOAD_CENTRAL_OFFICE_DEPARTMENTS_SUCCESS = 'LOAD_CENTRAL_OFFICE_DEPARTMENTS_SUCCESS';

//Staff
export const LOAD_STAFF_BY_EMPLOYEEID_SUCCESS = 'LOAD_STAFF_BY_EMPLOYEEID_SUCCESS';
export const LOAD_STAFFS_BY_CAMPUSID_SUCCESS = 'LOAD_STAFFS_BY_CAMPUSID_SUCCESS';

//Admin
export const LOAD_HOME_MESSAGE_SUCCESS = 'LOAD_HOME_MESSAGE_SUCCESS';
export const LOAD_HOME_MESSAGE_BY_ROLE_SUCCESS = 'LOAD_HOME_MESSAGE_BY_ROLE_SUCCESS';
export const LOAD_HOME_MESSAGE_BY_ROLE_WITHOUT_DATES_SUCCESS = 'LOAD_HOME_MESSAGE_BY_ROLE_WITHOUT_DATES_SUCCESS';
export const UPDATE_HOME_MESSAGE_SUCCESS = 'UPDATE_HOME_MESSAGE_SUCCESS';
export const CREATE_HOME_MESSAGE_SUCCESS = 'CREATE_HOME_MESSAGE_SUCCESS';
export const DELETE_HOME_MESSAGE_SUCCESS = 'DELETE_HOME_MESSAGE_SUCCESS';

//Voting Settings
export const LOAD_VOTING_SETTINGS_ACTIVE_YEAR_SUCCESS = 'LOAD_VOTING_SETTINGS_ACTIVE_YEAR_SUCCESS';
export const CREATE_VOTING_SETTINGS_SUCCESS = 'CREATE_VOTING_SETTINGS_SUCCESS';
export const UPDATE_VOTING_SETTINGS_SUCCESS = 'UPDATE_VOTING_SETTINGS_SUCCESS';
export const LOAD_ACTIVE_VOTING_SETTINGS_SUCCESS = 'LOAD_ACTIVE_VOTING_SETTINGS_SUCCESS';

//Candidates Search CO
export const LOAD_CANDIDATES_BY_EMP_ID_SUCCESS = 'LOAD_CANDIDATES_BY_EMP_ID_SUCCESS';
export const LOAD_CANDIDATE_BY_DEPARTMENT_ID_SUCCESS='LOAD_CANDIDATE_BY_DEPARTMENT_ID_SUCCESS';
export const LOAD_CANDIDATES_BY_EMP_NAME_SUCCESS='LOAD_CANDIDATES_BY_EMP_NAME_SUCCESS';

//Candidates Search Campuses
export const LOAD_CAMPUS_CANDIDATES_BY_EMP_ID_SUCCESS = 'LOAD_CAMPUS_CANDIDATES_BY_EMP_ID_SUCCESS';
export const LOAD_CAMPUS_CANDIDATES_BY_EMP_NAME_SUCCESS='LOAD_CAMPUS_CANDIDATES_BY_EMP_NAME_SUCCESS';

//Pay Grades
export const LOAD_PAY_GRADES_EMPLOYEE_SUCCESS = 'LOAD_PAY_GRADES_EMPLOYEE_SUCCESS';

// Candidate Nominees
export const CREATE_CANDIDATE_NOMINEES_SUCCESS = 'CREATE_CANDIDATE_NOMINEES_SUCCESS';
export const CREATE_CANDIDATE_NOMINEES_CENTRAL_OFFICE_SUCCESS = 'CREATE_CANDIDATE_NOMINEES_CENTRAL_OFFICE_SUCCESS';
export const DELETE_CANDIATE_NOMINEE_SUCCESS = 'DELETE_CANDIATE_NOMINEE_SUCCESS';
export const LOAD_CANDIDATE_NOMINEES_USING_CAMPUS_ID_SUCCESS = 'LOAD_CANDIDATE_NOMINEES_USING_CAMPUS_ID_SUCCESS';
export const LOAD_CANDIDATE_NOMINEES_BASED_ON_LOCATION_SUCCESS = 'LOAD_CANDIDATE_NOMINEES_BASED_ON_LOCATION_SUCCESS';

// Candidate Nominees All Campus
export const LOAD_CANDIDATE_NOMINEES_ALL_CAMPUS_SUCCESS = 'LOAD_CANDIDATE_NOMINEES_ALL_CAMPUS_SUCCESS';
// Locations
export const LOAD_LOCATIONS_SUCCESS = 'LOAD_LOCATIONS_SUCCESS';

// Candidate Types
export const LOAD_CANDIDATE_TYPES_SUCCESS = 'LOAD_CANDIDATE_TYPES_SUCCESS';

//Vote Eligibility
export const LOAD_VOTE_ELIGIBILITY_NON_CAMPUS_SUCCESS = 'LOAD_VOTE_ELIGIBILITY_NON_CAMPUS_SUCCESS';
export const LOAD_VOTE_ELIGIBILITY_CAMPUS_SUCCESS = 'LOAD_VOTE_ELIGIBILITY_CAMPUS_SUCCESS';

//Cast Votes
export const CREATE_CAST_VOTES_SUCCESS = 'CREATE_CAST_VOTES_SUCCESS';
export const CREATE_CAST_VOTES_FOR_CAMPUS_SUCCESS = 'CREATE_CAST_VOTES_FOR_CAMPUS_SUCCESS';

//User Selected Candidate Nominees
export const  LOAD_USER_SELECTED_CANDIDATE_NOMINEES_SUCCESS = 'LOAD_USER_SELECTED_CANDIDATE_NOMINEES_SUCCESS';




