export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//SharedActions
export const LOG_ERROR_SUCCESS = 'LOG_ERRROR_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_APP_PROPERTIES_SUCCESS = 'LOAD_APP_PROPERTIES_SUCCESS';
export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS';
export const LOAD_MENU_OPTIONS_SUCCESS = 'LOAD_MENU_OPTIONS_SUCCESS';
export const UPDATE_MENU_OPTIONS_SUCCESS = 'UPDATE_MENU_OPTIONS_SUCCESS';
export const UPDATE_USER_CAMPUS_SUCCESS = 'UPDATE_USER_CAMPUS_SUCCESS';
export const UPDATE_USER_HOME_PAGE_SUCCESS = 'UPDATE_USER_HOME_PAGE_SUCCESS';
export const LOAD_SCHOOLYEAR_TYPE_SUCCESS = 'LOAD_SCHOOLYEAR_TYPE_SUCCESS';

//Campus
export const LOAD_ALL_CAMPUSES_SUCCESS = 'LOAD_ALL_CAMPUSES_SUCCESS';
export const LOAD_CAMPUSES_BY_MANAGER_SUCCESS = 'LOAD_CAMPUSES_BY_MANAGER_SUCCESS';
export const LOAD_CAMPUSES_BY_STAFF_SUCCESS = 'LOAD_CAMPUSES_BY_STAFF_SUCCESS';
export const LOAD_CSO_CAMPUS_SUCCESS = 'LOAD_CSO_CAMPUS_SUCCESS';
export const LOAD_ALL_CSOS_SUCCESS = 'LOAD_ALL_CSOS_SUCCESS';
export const LOAD_CAMPUSTYPE_BY_CAMPUS_SUCCESS = 'LOAD_CAMPUSTYPE_BY_CAMPUS_SUCCESS';

//Staff
export const LOAD_STAFF_BY_EMPLOYEEID_SUCCESS = 'LOAD_STAFF_BY_EMPLOYEEID_SUCCESS';
export const LOAD_STAFFS_BY_CAMPUSID_SUCCESS = 'LOAD_STAFFS_BY_CAMPUSID_SUCCESS';

//Admin
export const LOAD_HOME_MESSAGE_SUCCESS = 'LOAD_HOME_MESSAGE_SUCCESS';
export const LOAD_HOME_MESSAGE_BY_ROLE_SUCCESS = 'LOAD_HOME_MESSAGE_BY_ROLE_SUCCESS';
export const LOAD_HOME_MESSAGE_BY_ROLE_WITHOUT_DATES_SUCCESS = 'LOAD_HOME_MESSAGE_BY_ROLE_WITHOUT_DATES_SUCCESS';
export const UPDATE_HOME_MESSAGE_SUCCESS = 'UPDATE_HOME_MESSAGE_SUCCESS';
export const CREATE_HOME_MESSAGE_SUCCESS = 'CREATE_HOME_MESSAGE_SUCCESS';
export const DELETE_HOME_MESSAGE_SUCCESS = 'DELETE_HOME_MESSAGE_SUCCESS';
export const LOAD_ALL_ANNUALSETUP_SUCCESS = 'LOAD_ALL_ANNUALSETUP_SUCCESS';
export const CREATE_ORGANIZATION_GROUP_SUCCESS = 'CREATE_ORGANIZATION_GROUP_SUCCESS';
export const CREATE_NEW_CALENDAR_SUCCESS = 'CREATE_NEW_CALENDAR_SUCCESS';
export const CREATE_CAMPUS_PROFILE_SUCCESS = 'CREATE_CAMPUS_PROFILE_SUCCESS';
export const CLEAR_ANNUAL_SETUP_SUCCESS = 'CLEAR_ANNUAL_SETUP_SUCCESS';
export const UPDATE_REPORT_CALENDAR_SUCCESS = 'UPDATE_REPORT_CALENDAR_SUCCESS';
export const CLEAR_REPORT_CALENDAR_SUCCESS = 'CLEAR_REPORT_CALENDAR_SUCCESS';
export const LOAD_ORGANIZATION_GROUP_SUCCESS = 'LOAD_ORGANIZATION_GROUP_SUCCESS';
export const UPDATE_ORGANIZATION_GROUP_SUCCESS = 'UPDATE_ORGANIZATION_GROUP_SUCCESS';
export const CLEAR_ORGANIZATION_GROUP_SUCCESS = 'CLEAR_ORGANIZATION_GROUP_SUCCESS';
export const LOAD_PUBLICORGANIZATION_GROUP_SUCCESS = 'LOAD_PUBLICORGANIZATION_GROUP_SUCCESS';
//Enrollment
export const LOAD_ALL_ENROLLMENTS_SUCCESS = 'LOAD_ALL_ENROLLMENTS_SUCCESS';
export const LOAD_ALL_ENROLLMENTSHISTORY_SUCCESS = 'LOAD_ALL_ENROLLMENTSHISTORY_SUCCESS';
export const LOAD_ALL_SCHOOLYEARS_SUCCESS = 'LOAD_ALL_SCHOOLYEARS_SUCCESS';
export const UPDATE_SCHOOL_YEAR_SUCCESS = 'UPDATE_SCHOOL_YEAR_SUCCESS';
export const LOAD_CURRENT_SCHOOLYEAR_SUCCESS = 'LOAD_CURRENT_SCHOOLYEAR_SUCCESS';
export const LOAD_ENROLLMENTS_BY_CAMPUS_SUCCESS = 'LOAD_ENROLLMENTS_BY_CAMPUS_SUCCESS';
export const CLEAR_CAMPUSES_SUCCESS = 'CLEAR_CAMPUSES_SUCCESS';
export const CLEAR_ENROLLMENTS_DATA_SUCCESS = 'CLEAR_ENROLLMENTS_DATA_SUCCESS';
export const LOAD_GRADE_LEVELS_BY_CAMPUS_SUCCESS = 'LOAD_GRADE_LEVELS_BY_CAMPUS_SUCCESS';
export const LOAD_CALENDAR_REPORT_DATES_SUCCESS = 'LOAD_CALENDAR_REPORT_DATES_SUCCESS';
export const LOAD_CALENDARS_SUCCESS = 'LOAD_CALENDARS_SUCCESS';
export const LOAD_ALL_CAMPUS_GRADE_LEVELS_SUCCESS = 'LOAD_ALL_CAMPUS_GRADE_LEVELS_SUCCESS';
export const UPDATE_ENROLLMENT_SUCCESS = 'UPDATE_ENROLLMENT_SUCCESS';
export const LOAD_CAMPUS_PROFILE_ID_SUCCESS = 'LOAD_CAMPUS_PROFILE_ID_SUCCESS';
export const CREATE_CAMPUS_ENROLLMENT_SUCCESS = 'CREATE_CAMPUS_ENROLLMENT_SUCCESS';
export const LOAD_CAMPUS_PROFILE_SUCCESS = 'LOAD_CAMPUS_PROFILE_SUCCESS';
export const UPDATE_CAMPUS_PROFILE_SUCCESS = 'UPDATE_CAMPUS_PROFILE_SUCCESS';
export const LOAD_ONE_ENROLLMENT_SUCCESS = 'LOAD_ONE_ENROLLMENT_SUCCESS';

//NonReporting Schools
export const LOAD_ALL_NONSCHOOLREPORTS_SUCCESS = 'LOAD_ALL_NONSCHOOLREPORTS_SUCCESS';
export const LOAD_ALL_COMPAREDAYSEQS_SUCCESS = 'LOAD_ALL_COMPAREDAYSEQS_SUCCESS';

//SummaryReport
export const LOAD_ALL_SUMMARYREPORTS_SUCCESS = 'LOAD_ALL_SUMMARYREPORTS_SUCCESS';
export const LOAD_SUMMARY_REPORT_SUCCESS = 'LOAD_SUMMARY_REPORT_SUCCESS';
//SummaryDetailReport
export const LOAD_ALL_SUMMARYDETAILREPORTS_SUCCESS = 'LOAD_ALL_SUMMARYDETAILREPORTS_SUCCESS';
export const LOAD_ALL_DETAILREPORTS_SUCCESS = 'LOAD_ALL_DETAILREPORTS_SUCCESS';
