/* Step #1 Create Database MSHP on any db server such as \\SQLDEV01\SPDEV,1435 */
DECLARE @dbname nvarchar(128)
SET @dbname = N'MSHP'
IF (EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE ('[' + name + ']' = @dbname OR name = @dbname)))
	ALTER DATABASE [MSHP] SET Single_User WITH Rollback Immediate

IF (EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE ('[' + name + ']' = @dbname OR name = @dbname)))
	DROP DATABASE [MSHP]
GO




CREATE DATABASE [MSHP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MSHP', FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL11.SPDEV\MSSQL\Data\MSHP-SIS-SP.mdf' , SIZE = 1024MB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024MB )
 LOG ON 
( NAME = N'MSHP_log', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL11.SPDEV\MSSQL\Data\MSHP-SIS-SP_log.ldf' , SIZE = 512MB , MAXSIZE = 2048GB , FILEGROWTH = 512MB )
GO

ALTER DATABASE [MSHP] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MSHP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MSHP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MSHP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MSHP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MSHP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MSHP] SET ARITHABORT OFF 
GO

ALTER DATABASE [MSHP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MSHP] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MSHP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MSHP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MSHP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MSHP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MSHP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MSHP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MSHP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MSHP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MSHP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MSHP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MSHP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MSHP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MSHP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MSHP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MSHP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MSHP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MSHP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MSHP] SET  MULTI_USER 
GO

ALTER DATABASE [MSHP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MSHP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MSHP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MSHP] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MSHP] SET  READ_WRITE 
GO


USE [MSHP]
GO

CREATE USER [U_MSHP] FOR LOGIN [U_MSHP] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [U_MSHP]
GO
