export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//SharedActions
export const LOG_ERROR_SUCCESS = 'LOG_ERRROR_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_APP_PROPERTIES_SUCCESS = 'LOAD_APP_PROPERTIES_SUCCESS';
export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS';
export const LOAD_MENU_OPTIONS_SUCCESS = 'LOAD_MENU_OPTIONS_SUCCESS';
export const UPDATE_MENU_OPTIONS_SUCCESS = 'UPDATE_MENU_OPTIONS_SUCCESS';
export const UPDATE_USER_CAMPUS_SUCCESS = 'UPDATE_USER_CAMPUS_SUCCESS';
export const UPDATE_USER_HOME_PAGE_SUCCESS = 'UPDATE_USER_HOME_PAGE_SUCCESS';

//Campus
export const LOAD_ALL_CAMPUSES_SUCCESS = 'LOAD_ALL_CAMPUSES_SUCCESS';
export const LOAD_CAMPUSES_BY_MANAGER_SUCCESS = 'LOAD_CAMPUSES_BY_MANAGER_SUCCESS';
export const GET_PRINCIPAL_NAME_SUCCESS = 'GET_PRINCIPAL_NAME_SUCCESS';
export const GET_CURRENT_SCHOOL_YEAR_SUCCESS = 'GET_CURRENT_SCHOOL_YEAR_SUCCESS';

//Staff
export const LOAD_STAFF_BY_EMPLOYEEID_SUCCESS = 'LOAD_STAFF_BY_EMPLOYEEID_SUCCESS';
export const LOAD_STAFFS_BY_CAMPUSID_SUCCESS = 'LOAD_STAFFS_BY_CAMPUSID_SUCCESS';

//Admin
export const LOAD_HOME_MESSAGE_SUCCESS = 'LOAD_HOME_MESSAGE_SUCCESS';
export const LOAD_HOME_MESSAGE_BY_ROLE_SUCCESS = 'LOAD_HOME_MESSAGE_BY_ROLE_SUCCESS';
export const LOAD_HOME_MESSAGE_BY_ROLE_WITHOUT_DATES_SUCCESS = 'LOAD_HOME_MESSAGE_BY_ROLE_WITHOUT_DATES_SUCCESS';
export const UPDATE_HOME_MESSAGE_SUCCESS = 'UPDATE_HOME_MESSAGE_SUCCESS';
export const CREATE_HOME_MESSAGE_SUCCESS = 'CREATE_HOME_MESSAGE_SUCCESS';
export const DELETE_HOME_MESSAGE_SUCCESS = 'DELETE_HOME_MESSAGE_SUCCESS';

//Word List
export const LOAD_WORD_LIST_SUCCESS =  'LOAD_WORD_LIST_SUCCESS';

//Word List Details
export const LOAD_WORD_LIST_DETAILS_SUCCESS = 'LOAD_WORD_LIST_DETAILS_SUCCESS';

//Schools List
export const LOAD_ALL_SCHOOLS_SUCCESS = 'LOAD_ALL_SCHOOLS_SUCCESS';
export const GET_SCHOOL_CAMPUS_DETAILS = 'GET_SCHOOL_CAMPUS_DETAILS';
export const SAVE_SCHOOL_DETAILS_SUCCESS = 'SAVE_SCHOOL_DETAILS_SUCCESS';

// waivers
export const LOAD_ALL_WAIVERS_SUCCESS = 'LOAD_ALL_WAIVERS_SUCCESS';
export const LOAD_ALL_SAVED_WAIVERS_SUCCESS = 'LOAD_ALL_SAVED_WAIVERS_SUCCESS';
export const CLEAR_ACTION = 'CLEAR_ACTION';
export const HANDLE_SELECTED_WAIVERS = 'HANDLE_SELECTED_WAIVERS';
export const SAVE_STATUS = 'SAVE_STATUS';
export const WAIVERS_EDIT_PERMISSION = 'WAIVERS_EDIT_PERMISSION';
export const SCHOOL_TYPE_SUCCESS = 'SCHOOL_TYPE_SUCCESS';
export const LOAD_ALL_CUSTOM_WAIVER_SUCCESS = 'LOAD_ALL_CUSTOM_WAIVER_SUCCESS';

//Application Administration
export const LOAD_ALL_WAIVERS_SETTING_SUCCESS = 'LOAD_ALL_WAIVERS_SETTING_SUCCESS';
export const POST_COPY_WAIVERS_SUCCESS = 'POST_COPY_WAIVERS_SUCCESS';

// General Waivers
export const LOAD_ALL_GENERAL_WAIVERS_SUCCESS = 'LOAD_ALL_GENERAL_WAIVERS_SUCCESS';

// Custom Waivers
export const LOAD_ALL_CUSTOM_WAIVERS_SUCCESS = 'LOAD_ALL_CUSTOM_WAIVERS_SUCCESS';

// send email
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';

// Waiver Request Details Form
export const LOAD_ALL_WAIVER_REQUEST_SUCCESS = 'LOAD_ALL_WAIVER_REQUEST_SUCCESS';
export const GET_REQUEST_FORM_DETAILS_SUCCESS = 'GET_REQUEST_FORM_DETAILS_SUCCESS';
export const GET_ADD_REQUEST_FORM_DETAILS_SUCCESS = 'GET_ADD_REQUEST_FORM_DETAILS_SUCCESS';
export const SUBMIT_WAIVER_REQUEST_SUCCESS = 'SUBMIT_WAIVER_REQUEST_SUCCESS';
export const GET_SSO_DETAILS_SUCCESS = 'GET_SSO_DETAILS_SUCCESS';
export const GET_SUP_DETAILS_SUCCESS = 'GET_SUP_DETAILS_SUCCESS';
export const CLEAR_REQUEST_FORM_ACTION = 'CLEAR_REQUEST_FORM_ACTION';
export const REMOVE_REQUEST_LIST = 'REMOVE_REQUEST_LIST';