export default {
    userProps: {
        user: {
            userName: "",
            firstName: "",
            lastName: "",
            fullName: "",
            loginId: "",
            employeeID: "",
            staffNaturalKey: "",
            role: "",
            roles: [],
            campusID: "",
            campusName: "",
            principalEmployeeID: "",
            principalName: "",
            principalLoginID: "",
            campusContacts: []
        },
        timeConfigurationID: 0,
        homePage: {
            type: "",
            content: null
        }
    },
    menuOptions: [],
    appProps: { title: "", siteCollection: "" },
    relationship: {},
    relationships: [],
    mentor: {},
    mentors: [],
    mentee: {},
    mentees: [],
    campuses: [],
    campusesWithCampusContact: [],
    campus:{},
    activityLog: {},
    activityLogs: [],
    activityLogsMentee: [],
    activityLogMentee: {},
    activityLogMentorCountPerMonth:'',
    activityCode: {},
    activityCodes: [],
    timeConfig: {},
    timeConfigs: [],
    cbmStandard: {},
    cbmStandards: [],
    activityStandards: [],
    mentoringTools: [],
    homeMessage: {},
    homeMessages: [],
    siteContent: {},
    siteContents: [],
    campusContact: {},
    campusContacts: [],
    menteeEndDate: {},
    menteesEndDates: [],
    mentorActivityLog:[],
    activityMentees: [],
    verificationCode: {},
    verificationCodeDetails: {},
    spUserProps: {},
    staff: {},
    staffs: [],
    csoStaffs: [],
    reportData: [],
    ajaxCallsInProgress: 0,
    errorMsg: '',
    activityType : {},
    topCampusesOnRelationShip : [],
    taskID: ''
};
