export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//SharedActions
export const LOG_ERROR_SUCCESS = 'LOG_ERRROR_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_APP_PROPERTIES_SUCCESS = 'LOAD_APP_PROPERTIES_SUCCESS';
export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS';
export const LOAD_MENU_OPTIONS_SUCCESS = 'LOAD_MENU_OPTIONS_SUCCESS';
export const UPDATE_MENU_OPTIONS_SUCCESS = 'UPDATE_MENU_OPTIONS_SUCCESS';
export const UPDATE_USER_CAMPUS_SUCCESS = 'UPDATE_USER_CAMPUS_SUCCESS';
export const UPDATE_USER_HOME_PAGE_SUCCESS = 'UPDATE_USER_HOME_PAGE_SUCCESS';

//Campus
export const LOAD_ALL_CAMPUSES_SUCCESS = 'LOAD_ALL_CAMPUSES_SUCCESS';
export const LOAD_CAMPUSES_BY_MANAGER_SUCCESS = 'LOAD_CAMPUSES_BY_MANAGER_SUCCESS';
export const LOAD_CAMPUSES_BY_STAFF_SUCCESS = 'LOAD_CAMPUSES_BY_STAFF_SUCCESS';

//Staff
export const LOAD_STAFF_BY_EMPLOYEEID_SUCCESS = 'LOAD_STAFF_BY_EMPLOYEEID_SUCCESS';
export const LOAD_STAFFS_BY_CAMPUSID_SUCCESS = 'LOAD_STAFFS_BY_CAMPUSID_SUCCESS';

//Admin
export const LOAD_HOME_MESSAGE_SUCCESS = 'LOAD_HOME_MESSAGE_SUCCESS';
export const LOAD_HOME_MESSAGE_BY_ROLE_SUCCESS = 'LOAD_HOME_MESSAGE_BY_ROLE_SUCCESS';
export const LOAD_HOME_MESSAGE_BY_ROLE_WITHOUT_DATES_SUCCESS = 'LOAD_HOME_MESSAGE_BY_ROLE_WITHOUT_DATES_SUCCESS';
export const UPDATE_HOME_MESSAGE_SUCCESS = 'UPDATE_HOME_MESSAGE_SUCCESS';
export const CREATE_HOME_MESSAGE_SUCCESS = 'CREATE_HOME_MESSAGE_SUCCESS';
export const DELETE_HOME_MESSAGE_SUCCESS = 'DELETE_HOME_MESSAGE_SUCCESS';
