export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

//SharedActions
export const LOG_ERROR_SUCCESS = 'LOG_ERRROR_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_APP_PROPERTIES_SUCCESS = 'LOAD_APP_PROPERTIES_SUCCESS';
export const UPDATE_USER_ROLE_SUCCESS = 'UPDATE_USER_ROLE_SUCCESS';
export const LOAD_MENU_OPTIONS_SUCCESS = 'LOAD_MENU_OPTIONS_SUCCESS';
export const UPDATE_MENU_OPTIONS_SUCCESS = 'UPDATE_MENU_OPTIONS_SUCCESS';
export const UPDATE_USER_CAMPUS_SUCCESS = 'UPDATE_USER_CAMPUS_SUCCESS';
export const UPDATE_USER_HOME_PAGE_SUCCESS = 'UPDATE_USER_HOME_PAGE_SUCCESS';
export const SEND_API_EMAIL_SUCCESS = 'SEND_API_EMAIL_SUCCESS';

//Mentors Actions
export const LOAD_MENTORS_BY_CAMPUS_SUCCESS = 'LOAD_MENTORS_BY_CAMPUS_SUCCESS';
export const LOAD_ALL_MENTORS_SUCCESS = 'LOAD_ALL_MENTORS_SUCCESS';
export const LOAD_MENTORS_IN_RELATIONSHIP_BY_CAMPUS_SUCCESS = 'LOAD_MENTORS_IN_RELATIONSHIP_BY_CAMPUS_SUCCESS';
export const LOAD_MENTORPROFILE_BY_EMPLOYEEID_SUCCESS = 'LOAD_MENTORPROFILE_BY_EMPLOYEEID_SUCCESS';
export const LOAD_MENTORPROFILE_BY_EMPLOYEEIDANDCAMPUSID_SUCCESS = 'LOAD_MENTORPROFILE_BY_EMPLOYEEIDANDCAMPUSID_SUCCESS';
// dashboard action
export const LOAD_MENTORAGREEMENTACCEPTENCESUMMARY_SUCCESS = 'LOAD_MENTORAGREEMENTACCEPTENCESUMMARY_SUCCESS';

//Mentees Actions
export const LOAD_MENTEES_BY_CAMPUS_SUCCESS = 'LOAD_MENTEES_BY_CAMPUS_SUCCESS';
export const LOAD_ALL_MENTEES_SUCCESS = 'LOAD_ALL_MENTEES_SUCCESS';
export const LOAD_MENTEES_IN_RELATIONSHIP_BY_CAMPUS_SUCCESS = 'LOAD_MENTEES_IN_RELATIONSHIP_BY_CAMPUS_SUCCESS';
export const LOAD_MENTEES_IN_RELATIONSHIP_BY_MENTORID_SUCCESS = 'LOAD_MENTEES_BY_CAMPUS_SUCCESS';
export const LOAD_MENTEERELATIONSHIPPROFILE_BY_EMPLOYEEID_SUCCESS = 'LOAD_MENTEERELATIONSHIPPROFILE_BY_EMPLOYEEID_SUCCESS';
export const LOAD_ALREADY_ADDED_MENTEES_BY_CAMPUS_SUCCESS = 'LOAD_ALREADY_ADDED_MENTEES_BY_CAMPUS_SUCCESS';

//Mentor/Mentee Relationships Actions
export const CREATE_RELATIONSHIP_SUCCESS = 'CREATE_RELATIONSHIP_SUCCESS';
export const CREATE_RELATIONSHIP_REQUEST_SUCCESS = 'CREATE_RELATIONSHIP_REQUEST_SUCCESS';
export const UPDATE_RELATIONSHIP_SUCCESS = 'UPDATE_RELATIONSHIP_SUCCESS';
export const UPDATE_RELATIONSHIP_REQUEST_SUCCESS = 'UPDATE_RELATIONSHIP_REQUEST_SUCCESS';

export const DELETE_RELATIONSHIP_SUCCESS = 'DELETE_RELATIONSHIP_SUCCESS';
export const LOAD_RELATIONSHIP_BY_ID_SUCCESS = 'LOAD_RELATIONSHIP_BY_ID_SUCCESS';
export const LOAD_RELATIONSHIPS_BY_CAMPUSID_SUCCESS = 'LOAD_RELATIONSHIPS_BY_CAMPUSID_SUCCESS';
export const LOAD_RELATIONSHIP_BY_MENTOR_AND_MENTEE_SUCCESS = 'LOAD_RELATIONSHIP_BY_MENTOR_AND_MENTEE_SUCCESS';
// dasborad: relationships
export const LOAD_RELATIONSHIPSTATUSSUMMARY_BY_CAMPUSID_SUCCESS = 'LOAD_RELATIONSHIPSTATUSSUMMARY_BY_CAMPUSID_SUCCESS';
export const LOAD_ALLRELATIONSHIPSCOUNTBYSTATUS_SUCCESS = 'LOAD_ALLRELATIONSHIPSCOUNTBYSTATUS_SUCCESS';
export const LOAD_TOPRELATIONSHIPSCAMPUSES_SUCCESS = 'LOAD_TOPRELATIONSHIPSCAMPUSES_SUCCESS';

//Campus
export const LOAD_ALL_CAMPUSES_SUCCESS = 'LOAD_ALL_CAMPUSES_SUCCESS';
export const LOAD_CAMPUSES_BY_MANAGER_SUCCESS = 'LOAD_CAMPUSES_BY_MANAGER_SUCCESS';
//dashboard action
export const LOAD_CAMPUSESUSINGMAS_SUCCESS = 'LOAD_CAMPUSESUSINGMAS_SUCCESS';
export const LOAD_ALLCAMPUSESWITHCAMPUSCONTACT_SUCCESS = 'LOAD_ALLCAMPUSESWITHCAMPUSCONTACT_SUCCESS';

//Staff
export const LOAD_STAFF_BY_EMPLOYEEID_SUCCESS = 'LOAD_STAFF_BY_EMPLOYEEID_SUCCESS';
export const LOAD_STAFFS_BY_CAMPUSID_SUCCESS = 'LOAD_STAFFS_BY_CAMPUSID_SUCCESS';
export const LOAD_ALLCSO_SUCCESS = 'LOAD_ALLCSO_SUCCESS';

//Activity Log
export const CLEAR_ACTIVITY_LOG_SUCCESS = 'CLEAR_ACTIVITY_LOG_SUCCESS';
export const LOAD_ALL_ACTIVITY_LOGS_SUCCESS = 'LOAD_ALL_ACTIVITY_LOGS_SUCCESS';
export const LOAD_ACTIVITY_LOGS_BY_CAMPUSID_SUCCESS = 'LOAD_ACTIVITY_LOGS_BY_CAMPUSID_SUCCESS';
export const LOAD_ACTIVITY_LOG_BY_ID_SUCCESS = 'LOAD_ACTIVITY_LOG_BY_ID_SUCCESS';
export const LOAD_ACTIVITY_LOGS_BY_MENTEEID_SUCCESS = 'LOAD_ACTIVITY_LOGS_BY_MENTEEID_SUCCESS';
export const CREATE_ACTIVITY_LOG_SUCCESS = 'CREATE_ACTIVITY_LOG_SUCCESS';
export const UPDATE_ACTIVITY_LOG_SUCCESS = 'UPDATE_ACTIVITY_LOG_SUCCESS';
export const DELETE_ACTIVITY_LOG_SUCCESS = 'DELETE_ACTIVITY_LOG_SUCCESS';
export const LOAD_ACTIVITY_LOG_MENTEE_BY_ID_SUCCESS = 'LOAD_ACTIVITY_LOG_MENTEE_BY_ID_SUCCESS';
export const UPDATE_ACTIVITY_LOG_MENTEE_SUCCESS = 'UPDATE_ACTIVITY_LOG_MENTEE_SUCCESS';
export const LOAD_MENTEE_ACTIVITY_LOG_BY_ID_SUCCESS = 'LOAD_MENTEE_ACTIVITY_LOG_BY_ID_SUCCESS';
//dashboard
export const LOAD_ALL_ACTIVITY_LOGHOURSMONTHLY_SUCCESS = 'LOAD_ALL_ACTIVITY_LOGHOURSMONTHLY_SUCCESS';

//Activity Mentees
export const LOAD_ALL_ACTIVITY_MENTEES_SUCCESS = 'LOAD_ALL_ACTIVITY_MENTEES_SUCCESS';
export const NEW_ADD_ACTIVITY_MENTEE_SUCCESS = 'NEW_ADD_ACTIVITY_MENTEE_SUCCESS';
export const NEW_ADD_ACTIVITY_MENTEES_SUCCESS = 'NEW_ADD_ACTIVITY_MENTEES_SUCCESS';
export const NEW_DELETE_ACTIVITY_MENTEE_SUCCESS = 'NEW_DELETE_ACTIVITY_MENTEE_SUCCESS';
export const NEW_DELETE_ACTIVITY_MENTEE_EDIT_SUCCESS = 'NEW_DELETE_ACTIVITY_MENTEE_EDIT_SUCCESS';
export const NEW_DELETE_ALL_ACTIVITY_MENTEE_SUCCESS = 'NEW_DELETE_ALL_ACTIVITY_MENTEE_SUCCESS';

//Activity Log Mentor Count Prr Month
export const LOAD_ACTIVITY_LOG_MENTOR_COUNT_PER_MONTH_SUCCESS = 'LOAD_ACTIVITY_LOG_MENTOR_COUNT_PER_MONTH_SUCCESS';
//SPUseProperties actions
export const LOAD_SP_USER_PROPS_SUCCESS = 'LOAD_SP_USER_PROPS_SUCCESS';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';

//Admin
export const LOAD_ALL_TIME_CONFIGS_SUCCESS = 'LOAD_ALL_TIME_CONFIGS_SUCCESS';
export const LOAD_TIME_CONFIG_SUCCESS = 'LOAD_TIME_CONFIG_SUCCESS';
export const LOAD_CURRENT_TIME_CONFIG_SUCCESS = 'LOAD_CURRENT_TIME_CONFIG_SUCCESS';
export const LOAD_TIME_CONFIG_BY_SCHOOL_YEAR_SUCCESS = 'LOAD_TIME_CONFIG_BY_SCHOOL_YEAR_SUCCESS';
export const CREATE_TIME_CONFIG_SUCCESS = 'CREATE_TIME_CONFIG_SUCCESS';
export const UPDATE_TIME_CONFIG_SUCCESS = 'UPDATE_TIME_CONFIG_SUCCESS';
export const DELETE_TIME_CONFIG_SUCCESS = 'DELETE_TIME_CONFIG_SUCCESS';
export const LOAD_ALL_ACTIVITY_CODES_SUCCESS = 'LOAD_ALL_ACTIVITY_CODES_SUCCESS';
export const LOAD_ACTIVITY_CODE_BY_NAME_SUCCESS = 'LOAD_ACTIVITY_CODE_BY_NAME_SUCCESS';
export const UPDATE_ACTIVITY_CODE_SUCCESS = 'UPDATE_ACTIVITY_CODE_SUCCESS';
export const DELETE_ACTIVITY_CODE_SUCCESS = 'DELETE_ACTIVITY_CODE_SUCCESS';
export const LOAD_ACTIVITY_CODE_SUCCESS = 'LOAD_ACTIVITY_CODE_SUCCESS';
export const CREATE_ACTIVITY_CODE_SUCCESS = 'CREATE_ACTIVITY_CODE_SUCCESS';
export const LOAD_ALL_CBM_STANDARDS_SUCCESS = 'LOAD_CBM_STANDARDS_SUCCESS';
export const LOAD_CBM_STANDARD_SUCCESS = 'LOAD_CBM_STANDARD_SUCCESS';
export const UPDATE_CBM_STANDARD_SUCCESS = 'UPDATE_CBM_STANDARD_SUCCESS';
export const LOAD_ALL_ACTIVITY_STANDARDS_SUCCESS = 'LOAD_ALL_ACTIVITY_STANDARDS_SUCCESS';
export const LOAD_ALL_MENTORING_TOOLS_SUCCESS = 'LOAD_ALL_MENTORING_TOOLS_SUCCESS';
export const LOAD_ALL_HOME_MESSAGES_SUCCESS = 'LOAD_ALL_HOME_MESSAGES_SUCCESS';
export const LOAD_HOME_MESSAGE_SUCCESS = 'LOAD_HOME_MESSAGE_SUCCESS';
export const LOAD_HOME_MESSAGE_BY_ROLE_SUCCESS = 'LOAD_HOME_MESSAGE_BY_ROLE_SUCCESS';
export const LOAD_HOME_MESSAGE_BY_ROLE_WITHOUT_DATES_SUCCESS = 'LOAD_HOME_MESSAGE_BY_ROLE_WITHOUT_DATES_SUCCESS';
export const UPDATE_HOME_MESSAGE_SUCCESS = 'UPDATE_HOME_MESSAGE_SUCCESS';
export const CREATE_HOME_MESSAGE_SUCCESS = 'CREATE_HOME_MESSAGE_SUCCESS';
export const DELETE_HOME_MESSAGE_SUCCESS = 'DELETE_HOME_MESSAGE_SUCCESS';
export const LOAD_ALL_SITE_CONTENTS_SUCCESS = 'LOAD_ALL_SITE_CONTENTS_SUCCESS';
export const LOAD_SITE_CONTENT_SUCCESS = 'LOAD_SITE_CONTENT_SUCCESS';
export const LOAD_SITE_CONTENT_BY_CODE_SUCCESS = 'LOAD_SITE_CONTENT_BY_CODE_SUCCESS';
export const UPDATE_SITE_CONTENT_SUCCESS = 'UPDATE_SITE_CONTENT_SUCCESS';
export const CREATE_SITE_CONTENT_SUCCESS = 'CREATE_SITE_CONTENT_SUCCESS';
export const DELETE_SITE_CONTENT_SUCCESS = 'DELETE_SITE_CONTENT_SUCCESS';
export const UPDATE_MENTOR_AGREEMENT_PDF_SUCCESS='UPDATE_MENTOR_AGREEMENT_PDF_SUCCESS';
export const LOAD_ALL_CAMPUS_CONTACTS_SUCCESS = 'LOAD_ALL_CAMPUS_CONTACTS_SUCCESS';
export const LOAD_CAMPUS_CONTACTS_BY_CAMPUSID_SUCCESS = 'LOAD_CAMPUS_CONTACTS_BY_CAMPUSID_SUCCESS';
export const CREATE_CAMPUS_CONTACT_SUCCESS = 'CREATE_CAMPUS_CONTACT_SUCCESS';
export const UPDATE_CAMPUS_CONTACT_SUCCESS = 'UPDATE_CAMPUS_CONTACT_SUCCESS';
export const DELETE_CAMPUS_CONTACT_SUCCESS = 'DELETE_CAMPUS_CONTACT_SUCCESS';
export const LOAD_CAMPUS_CONTACT_BY_CAMPUSID_AND_EMPLOYEEID_SUCCESS = 'LOAD_CAMPUS_CONTACT_BY_CAMPUSID_AND_EMPLOYEEID_SUCCESS';
export const LOAD_ALL_MENTEES_ENDDATES_SUCCESS = 'LOAD_ALL_MENTEES_ENDDATES_SUCCESS';
export const LOAD_MENTEES_ENDDATES_BY_CAMPUSID_SUCCESS = 'LOAD_MENTEES_ENDDATES_BY_CAMPUSID_SUCCESS';
export const LOAD_MENTEE_ENDDATE_BY_EMPLOYEEID_SUCCESS = 'LOAD_MENTEE_ENDDATE_BY_EMPLOYEEID_SUCCESS';
export const UPDATE_MENTEE_ENDDATE_SUCCESS = 'UPDATE_MENTEE_ENDDATE_SUCCESS';
export const DELETE_MENTEE_ENDDATE_SUCCESS = 'DELETE_MENTEE_ENDDATE_SUCCESS';
export const CREATE_MENTEE_ENDDATE_SUCCESS = 'CREATE_MENTEE_ENDDATE_SUCCESS';
export const LOAD_ALL_ACTIVITY_TYPE = 'LOAD_ALL_ACTIVITY_TYPE';
//////
export const CREATE_ACTIVITY_STANDARD_SUCCESS = "CREATE_ACTIVITY_STANDARD_SUCCESS";
export const UPDATE_ACTIVITY_TYPE_SUCCESS ="UPDATE_ACTIVITY_TYPE_SUCCESS";

export const CREATE_VERIFICATION_CODE_DETAILS_SUCCESS = 'CREATE_VERIFICATION_CODE_DETAILS_SUCCESS';
export const LOAD_VERIFICATION_CODE_DETAILS_SUCCESS = 'LOAD_VERIFICATION_CODE_DETAILS_SUCCESS';
export const UPDATE_VERIFICATION_CODE_DETAILS_SUCCESS = 'UPDATE_VERIFICATION_CODE_DETAILS_SUCCESS';
export const DELETE_VERIFICATION_CODE_DETAILS_SUCCESS = 'DELETE_VERIFICATION_CODE_DETAILS_SUCCESS';
export const LOAD_VERIFICATION_CODE_BY_PARENT_CODE_SUCCESS = 'LOAD_VERIFICATION_CODE_BY_PARENT_CODE_SUCCESS';

//Reports
export const CLEAR_REPORT_DATA_SUCCESS = 'CLEAR_REPORT_DATA_SUCCESS';
export const LOAD_DEMOGRAPHIC_REPORT_SUCCESS = 'LOAD_DEMOGRAPHIC_REPORT_SUCCESS';
export const LOAD_MENTOR_ACTIVITY_LOG_REPORT_SUCCESS = 'LOAD_MENTOR_ACTIVITY_LOG_REPORT_SUCCESS';
export const LOAD_ACTIVITY_TOTAL_REPORT_SUCCESS = 'LOAD_ACTIVITY_TOTAL_REPORT_SUCCESS';
export const LOAD_ACTIVITY_LOG_VERIFICATION_REPORT_SUCCESS = 'LOAD_ACTIVITY_LOG_VERIFICATION_REPORT_SUCCESS';

//MentorActivityLog
export const CREATE_MENTOR_ACTIVITY_LOG_SUCCESS = 'CREATE_MENTOR_ACTIVITY_LOG_SUCCESS';
export const UPDATE_MENTOR_ACTIVITY_LOG_SUCCESS = 'UPDATE_MENTOR_ACTIVITY_LOG_SUCCESS';
export const LOAD_ALL_MENTEE_ACTIVITY_SUCCESS = 'LOAD_ALL_MENTEE_ACTIVITY_SUCCESS';
export const LOAD_ALL_MENTOR_AGREEMENT_SUCCESS = 'LOAD_ALL_MENTOR_AGREEMENT_SUCCESS';

//Mentor Agreement Task ID
export const GET_TASK_ID_SUCCESS = 'GET_TASK_ID_SUCCESS';





